# Defina a porta na qual o servidor deve ser iniciado
port: 25365
# Defina a quantidade de threads do pool
poolSize: 4
# Defina o delay para limpeza de mensagens jรก vistas ou antigas demais
cleanDelay: 5 # em segundos